name: fern_seg
channels:
  - conda-forge
  - pytorch
  - fastai
  - bioconda
dependencies:
  - pillow=5.3.0
  - pytorch=1.1.0
  - torchvision=0.3.0
  - cpuonly
  - fastai=1.0.55
  - matplotlib=3.0.3
  - plantcv=3.6.0
  - notebook
